services:
  api:
    build: .
    container_name: dumbpass
    ports:
      - "8000:80"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=1
    depends_on:
      - db
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 80 --reload

  db:
    image: postgres:15
    container_name: password_manager_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: