version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "%(asctime)s [%(name)s | %(levelname)s] - %(message)s"

  colored:
    class: colorlog.ColoredFormatter
    format: "%(asctime)s [%(log_color)s%(levelname)s%(reset)s | %(name)s] - %(message)s"
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: "red,bg_white"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout

root:
  level: WARN
  handlers: [console]
  propagate: no

loggers:
  src:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
  gunicorn:
    level: INFO
    handlers: [console]
    propagate: no
  gunicorn.access:
    level: INFO
    handlers: [console]
    propagate: no
